<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Mermaider/Mermaider.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures\mermaid.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
